### ISSUE TITLE
Feature/Management command (`cleanup_files`)

### ISSUE THREAD

**Issue by barseghyanartur** [un1t/django-cleanup#104]
I see an old issue which is closed for comments: https://github.com/un1t/django-cleanup/issues/19. 

Why is this not yet implemented? So simple, yet so useful.

**Comment by vinnyrose** [comment]
I understand the request, as I have personally developed a command for a client that accomplishes what was requested in #19. In my view, such a command should be custom written to accommodate the specific system it operates within. It seems impractical for this app to offer that functionality without significantly increasing the workload to cater to each unique system. While it may be straightforward for the use case you have in mind, I believe it would not be as simple for all possible scenarios. Consequently, this is beyond the scope of this app. This app excels at one function, and I see no necessity for it to expand into another.
