### ISSUE TITLE
ImportError using django 1.6.5

### ISSUE THREAD

**Issue by fabiocaccamo** [un1t/django-cleanup#18]
[...]/lib/python2.7/site-packages/django_cleanup/models.py", line 3, in <module>
from django.apps import apps
ImportError: No module named apps

**Comment by un1t** [comment]
now it fixed.

**Comment by fabiocaccamo** [comment]
could you release a 0.3.1 to install trought pip ?
thanks

**Comment by un1t** [comment]
It is already there 
https://pypi.python.org/pypi?:action=display&name=django-cleanup&version=0.3.1
