### ISSUE TITLE
Add tagged releases.

### ISSUE THREAD

**Issue by vinnyrose** [un1t/django-cleanup#23]
Please add tags to each version so we can better track them. (Only a repo committer can run these)

    git tag -a 0.1.0 0fada14463 -m ''
    git tag -a 0.1.4 6440f588d4 -m ''
    git tag -a 0.1.5 57ec98ae31 -m ''
    git tag -a 0.1.6 69a5840949 -m ''
    git tag -a 0.1.7 c8f6484153 -m ''
    git tag -a 0.1.8 031262d702 -m ''
    git tag -a 0.1.9 6adeedba94 -m ''
    git tag -a 0.1.10 715d0fcdfb -m ''
    git tag -a 0.1.11 40b2983f53 -m ''
    git tag -a 0.1.12 d9989d3f30 -m ''
    git tag -a 0.1.13 a0901e54b1 -m ''
    git tag -a 0.2.0 1902f18ca9 -m ''
    git tag -a 0.2.1 bc4925d487 -m ''
    git tag -a 0.3.0 6fb0e518fe -m ''
    git tag -a 0.3.1 9c4ed988a4 -m ''
    git tag -a 0.4.0 2bb0ffe48a -m ''
    git push --tags

If you want to check, these should link to their commits:
0.1.0: 0fada14463
0.1.4: 6440f588d4
0.1.5: 57ec98ae31
0.1.6: 69a5840949
0.1.7: c8f6484153
0.1.8: 031262d702
0.1.9: 6adeedba94
0.1.10: 715d0fcdfb
0.1.11: 40b2983f53
0.1.12: d9989d3f30
0.1.13: a0901e54b1
0.2.0: 1902f18ca9
0.2.1: bc4925d487
0.3.0: 6fb0e518fe
0.3.1: 9c4ed988a4
0.4.0: 2bb0ffe48a

**Comment by un1t** [comment]
Done!
