### ISSUE TITLE
Documentation needs improvement.

### ISSUE THREAD

**Issue by mstyvane** [un1t/django-cleanup#33]
Hello Ilya! 

For example if I have a model that look like this:

```
class Profile(models.Model):
    name = models.CharField(max_length=40)
    doc = models.FieldField(upload_to='folder')
```

The documentation doesn't say how one should use the signals an not every projects need sorl-thumbnail

**Comment by un1t** [comment]
Hi!
You don't need to use signals in this case.

**Comment by mstyvane** [comment]
What I did is simply  call `os.remove(kwargs['file'])` in my callback.

**Comment by vinnyrose** [comment]
The purpose of signals is to interact with third-party API's. If you don't need to interact with third parties then you don't need to use the signal interface. This library will handle the deletion of files for you (using django's File object API), you don't need to call `os.remove` yourself.

**Comment by mstyvane** [comment]
@vinnyrose Hi, that is what I thought but I can see that the [test app](https://github.com/un1t/django-cleanup/blob/master/django_cleanup/testapp/models.py#L36-L40) explicitly deleted the file in the callback passed to the signal. 

Can you then please tell me how I should use the signal if my model looks like the example above?

**Comment by vinnyrose** [comment]
For the model above, you don't need to use signals.

The code you are referencing in the test app is not explicitly deleting the file, it is calling an API function (`delete`) provided by sorl_thumbnail which deletes thumbnail files (related to but separate from the original file) and clears caches used internal in the sorl_thumbnail app.

The actual deletion of the original file [happens here](https://github.com/un1t/django-cleanup/blob/master/django_cleanup/handlers.py#L92).

For most developers, including yourself, you simple `pip install django-cleanup` then add `django_cleanup` to `INSTALLED_APPS` and it will work as specified.

**Comment by mstyvane** [comment]
@vinnyrose Oh that is it :smile:Thank you!

**Comment by yo1995** [comment]
> Hi!
> You don't need to use signals in this case.

Maybe you can mention this in README, so that people will know for native app, it doesn't need to add any extra code to use this module.
