### ISSUE TITLE
Add documentation regarding TestCase vs TransactionalTestCase

### ISSUE THREAD

**Issue by McPo** [un1t/django-cleanup#38]
Discovered that TestCases must use TransactionalTestCase, in order for the library to work. Might be worth explicitly mentioning this.

**Comment by Marviel** [comment]
Bump. Docs here: https://docs.djangoproject.com/en/2.0/topics/testing/tools/#django.test.TransactionTestCase

**Comment by vinnyrose** [comment]
also: https://docs.djangoproject.com/en/2.1/topics/db/transactions/#use-in-tests

**Comment by vinnyrose** [comment]
Section added to README to document this.
