### ISSUE TITLE
Data loss if same file is saved in multiple fields

### ISSUE THREAD

**Issue by singhravi1** [un1t/django-cleanup#44]
If a file is saved in multiple instances, then removing a single instance removes the file and cause 'file not found' error for every other instance.

We need to check if the file is referenced in any other object before deleting.

**Comment by vinnyrose** [comment]
If I understand what you suggesting, this app would have to load all data in the database and search all of it before deleting any file. Please correct me if I am misunderstanding. But if what I understood is the case then I think this would be firmly a "wontfix".

Multiple instances referencing the same file is not a case that is supported and I would recommend you consider using a file manager app that centralizes references to a file such as django-filer or django-filebrowser or roll your own that supports your use case.

**Comment by singhravi1** [comment]
Okay. I understand.

Can you suggest, how can i delete an instance without deleting its associated file?

**Comment by vinnyrose** [comment]
Will this issue be solved when the “don’t delete default file” feature is merged to master? Or is this a different issue from that?

**Comment by singhravi1** [comment]
I dont think so.

Besides, the issue would actually be a 'wontfix' if we have to search every FileField in database before deleting a file.

This case is, i think, not common, that same image would be referenced in multiple models. For this, i have added a setting field which specifies a list of model names for which file should not be deleted. This was the patch for my situation.

**Comment by vinnyrose** [comment]
resolved with #47
