### ISSUE TITLE
Test with Django 2.2

### ISSUE THREAD

**Issue by texnic** [un1t/django-cleanup#49]
Saw indications that it works with Django 2.2?  Is it approved for 2.2 and maintained?

It's a very useful tool, but it's dangerous (can be data-destructive), so I would only use it if it's maintained.

**Comment by vinnyrose** [comment]
All tests pass on Django 2.2 and have been passing since February for py3.5, py3.6 and py3.7 (since beta line). I will work on updating the README.

**Comment by vinnyrose** [comment]
New version released with updated README on current supported Django versions.
