### ISSUE TITLE
django-cleanup remove default image in models when cleanup

### ISSUE THREAD

**Issue by Lifechess** [un1t/django-cleanup#66]
i use python 3.6 and dango 2.0 , i got some default image i would like to ignore in my models, is there a way please?

**Comment by vinnyrose** [comment]
Are you using the "default" field on the file field? https://docs.djangoproject.com/en/3.0/ref/models/fields/#default

Example here:
https://github.com/un1t/django-cleanup/blob/17336bb6cf8a103d5a9a18f5e862ebb16366529f/django_cleanup/testapp/models/app.py#L25

**Comment by Lifechess** [comment]
I'm using imageField

`image1 = models.ImageField(upload_to='media/', default='shadow1.jpg')`

**Comment by vinnyrose** [comment]
Whatever the default value is when it is stored in the db, the default needs to be that value exactly. I'm thinking it would have to be `image1 = models.ImageField(upload_to='media/', default='media/shadow1.jpg')`?

**Comment by Lifechess** [comment]
still the same when i delete the ads default is remove in media

**Comment by vinnyrose** [comment]
Which version of django-cleanup are you on? Support for the default field was added in version 3.1.0

Are you using the default file storage backing?
Is the path you have configured in `upload_to` and file configured in `default` relative to the MEDIA_ROOT setting?

**Comment by Lifechess** [comment]
thanks ! the problem was my version, it was 3.0.1 , i tested it and it work fine now
