### ISSUE TITLE
Deletes unwanted files

### ISSUE THREAD

**Issue by harshraj22** [un1t/django-cleanup#68]
I have a model having ImageField (default to some image). When the ImageField is updated by any instance of the model, the default image is deleted. This causes problems when many instances of same model are linked with default image, and one of them updates.

Reference: 
[my project](https://github.com/harshraj22/CSE_HUB) Develop branch, Profile model.

**Comment by vinnyrose** [comment]
is this a typo:
```
profile_pic = models.ImageField(storage=fs, upload_to='profile_pics', default='defalut.png')
                                                                                   ^^
```

**Comment by harshraj22** [comment]
@vinnyrose :sweat_smile: Yes. It is, but even after solving this, the `default.png` is deleted from `profile_pics`

**Comment by vinnyrose** [comment]
Have you tried a default of `default='profile_pics/default.png'` ? I always forget what that field is relative to.

**Comment by harshraj22** [comment]
Well, due to `upload_to` argument, it will simply create another directory inside `profile_pics`. :man_shrugging:

**Comment by vinnyrose** [comment]
I can't tell if you made an assumption with your last statement or if you tested the suggestion and it didn't work. If it was an assumption and the suggestion worked please close the issue. Thanks.

**Comment by harshraj22** [comment]
@vinnyrose sry. It works . Thanks ! Though I don't understand how. Can you explain a little ?
