### ISSUE TITLE
Have option to use django-cleanup explicitly on models

### ISSUE THREAD

**Issue by daviddavis** [un1t/django-cleanup#75]
By default, django-cleanup works by cleaning all models unless you explicitly ignore them with `@cleanup.ignore`. I'm wondering if django-cleanup could work in such a way that it doesn't cleanup any models unless you explicitly ask it to?

For example:

```python
@cleanup.cleanup
class UserImage(models.Model):
    image = models.FileField()
```

**Comment by wlisesrivas** [comment]
Maybe extends from some class instead? 
`class UserImage(cleanup.CleanUp, models.Model):
    image = models.FileField()`

**Comment by vinnyrose** [comment]
My initial thought is that the implementation would follow the way that `cleanup.ignore` is implemented as a decorator.

Then add additional configuration in addition to the default `django_cleanup.apps.CleanupConfig` (which is what one adds to INSTALLED_APPS) so then there would be two configs:

`django_cleanup.apps.CleanupConfig`: current default behavior, cleans all, ignore model using `@cleanup.ignore`.

`django_cleanup.apps.CleanupSelectedConfig`: only cleans selected, select model using `@cleanup.cleanup`.

Not sure about the extends method, it would seem to bring in defining how it works with inheritance. Right now  `@cleanup.ignore` does not mark subclasses as ignored.

**Comment by daviddavis** [comment]
@vinnyrose that sounds like a fine solution. 

FWIW, our project decided to use django-cleanup as it is and add `@cleanup.ignore` to the models we want to ignore. So we no longer need this.

**Comment by c0d33py** [comment]
hello! i am using django-cleanup. 
i have a problem with it! when i try to create a new story every time FileField show error (file is required). i also define `null=True` in file attribute `file_data = models.FileField(upload_to='stories', null=True, blank=True)`

**Comment by alimp5** [comment]
Greetings !

sorry for SPAM message.

but i would say thank you to django-cleanup developers ;X

Tnx a lot for this module :XXXXX

**Comment by UDAR-TomH** [comment]
@vinnyrose That solution sounds great, and I would still love to see it implemented, if it is still in the works.
