### ISSUE TITLE
In production django-cleanup with aws s3 is not working

### ISSUE THREAD

**Issue by Lifechess** [un1t/django-cleanup#78]
I make some test with s3 storage but not working
is there some code to add to make it work with s3 storage ?

**Comment by vinnyrose** [comment]
If you are asking about how to write tests please refer to the "How to write tests" section in the readme: https://github.com/un1t/django-cleanup#how-to-write-tests

If not, please give more details about what issue you are seeing.

**Comment by Lifechess** [comment]
no, it's just that the images is not deleting in the bucket aws s3

**Comment by vinnyrose** [comment]
Please post what version of Django and Django-cleanup you are using. And if you are using a custom built storage backend or a storage backend package that is open source.

Make sure to check the troubleshooting section of the README: https://github.com/un1t/django-cleanup#troubleshooting

As well you can check logs for exceptions, for file deletion exceptions the app logs a message of the format:
```
logger.exception(
   'There was an exception deleting the file `%s` on field `%s.%s.%s`',
   file_, opts.app_label, opts.model_name, field_name)
```

(https://docs.djangoproject.com/en/dev/topics/logging/)

**Comment by Lifechess** [comment]
I find the problem, my local website doesn't delete production static only production website can delete it even if both are related
thanks for the help !!
