### ISSUE TITLE
Deletes Files shared between instances

### ISSUE THREAD

**Issue by Ri-Dearg** [un1t/django-cleanup#79]
I've discovered that if two models instances share a single file, and one of the instances is deleted, the file is also deleted. Obviously this creates  an issue when trying to parse the model as the reference to the file remains, while the file does not.

**Comment by vinnyrose** [comment]
Hello,

This issue has been brought up previously in https://github.com/un1t/django-cleanup/issues/51.

My position and recommendations from that issue have not changed. This is not something that can be supported within this Django app.

**Comment by Ri-Dearg** [comment]
Not even for the same model? The program seems to pull in the model and checks it for a FileField before dealing with the instance. Would it not be able to check other instances of the same model for the same string? If the same string is present, it's skipped. I can see why it would be difficult cross-model though.

Would it be possible to get all instances of that particular model and check their file field? 

I have my files categorised by model, so some images are utilised between instances, but only for that model. I think it is still a nice storage solution which gives a balance between optimisation and utility. I think the inability to utilise one file for numerous models is a bit of a limitation for optimisation. The flexibility within the app would be useful.

If what I'm saying is possible at all, let me know. I would do a pull request for it, but I'm not so skilled as to be able to just jump in, I'd need some indication as to which function I should be looking at.

**Comment by vinnyrose** [comment]
It is not within the scope of this app to do something as complex as load from the database and search every instance of a model each time a model or its file field changes.

The only case of a file being used across instances of the same model that is supported by this app is if there is a "default" file specified for a file field. A properly specified default file for a file field will not be deleted:
https://github.com/un1t/django-cleanup/blob/91630b4e98f47626997da016cd13a70099d1ebc2/django_cleanup/handlers.py#L80-L84

If this isn't the case of "default" files I would recommend a file manager to be used for fields that are going to share reference to the same file: https://djangopackages.org/grids/g/file-managers/

**Comment by Ri-Dearg** [comment]
Fair enough, I can see why that's not a useful implementation for larger DBs. But "not within the scope" is not the same as "cannot be supported".

I'm asking, from the knowledge of the person that has built the app, can what I suggested be done within the app? I'm looking at cache.py and thinking it could be, but I don't want to dive in and discover its a useless endeavour. 

For what I'm building, a file manager is unnecessary. I just want a simple solution that deletes unused images, while maintaining filenames. This is for the end user, not for me, so adding file managers is adding unnecessary complexity. The solution just needs to handle itself cleanly and simply with flexibility. Your app has the clean simplicity but I need more flexibility. There's only ever a very small number of models in the database, so it's not querying anything complex in my use case. 

If the app can do that, please just give me an indication and I'll take it from there for my own fork and close this. It would be very useful to me in my projects. I appreciate your help, thank you.

**Comment by vinnyrose** [comment]
From a product standpoint it can't be supported in django-cleanup without increasing the scope of the project. But technically it should be possible to add additional logic in handlers.py `delete_file` and return before deleting the file.

**Comment by Ri-Dearg** [comment]
Okay, that's perfect, Mario. Thank you very much!

**Comment by LennyLip** [comment]
https://docs.djangoproject.com/en/3.1/releases/1.3/#deleting-a-model-doesn-t-delete-associated-files

The simplest solution is to remove

**Comment by LennyLip** [comment]
https://docs.djangoproject.com/en/3.1/releases/1.3/#deleting-a-model-doesn-t-delete-associated-files

> In earlier Django versions, when a model instance containing a FileField was deleted, FileField took it upon itself to also delete the file from the backend storage. This opened the door to several data-loss scenarios, including rolled-back transactions and **fields on different models referencing the same file.**

It was the reason, why the Django team excluded file deletion. So, django-cleanup doesn't worry about this scenario. I think this information needs to be added to the docs.

What about rolled-back transactions? It seems it's' supported.

The simplest solution, that the Django team suggests using is to remove files with a management command and a cron task (something like django-unused-media application). But running the command depends on the database size and on the media folder size, which can quickly become problematic once they increase.
