### ISSUE TITLE
Check uniqueness before delete?

### ISSUE THREAD

**Issue by tonypottera24** [un1t/django-cleanup#85]
I'm using django 3.2.
Assume we have a Image model, which includes a ImageField to save image.
On my local computer, if I create two Image objects and save image.jpg twice, it will produce two files.

* image.jpg
* image_ABCDE.jpg

However, on google cloud storage. https://django-storages.readthedocs.io/en/latest/backends/gcloud.html
Storing image.jpg twice will only produce one file.

* image.jpg

As a result, if I delete one Image object, another Image object cannot find the image.jpg file.
It would be nice if django-cleanup can provide an option to explicitly scan the uniqueness of the file.

**Comment by tonypottera24** [comment]
Is there any way to override the delete function and add the check by myself?

**Comment by vinnyrose** [comment]
This won't be supported in this library directly, as the ability to do this already exists in the django storage backend api.

To override the delete method you can subclass your storage backend (the "GoogleCloudStorage") to change how it names files or how the delete works.

**Comment by tonypottera24** [comment]
@vinnyrose thanks for your explanation.
Do you mean, django-cleanup will call the delete method when the object delete.
If I don't want to delete the object, I can override the delete method to stop the deletion?
