### ISSUE TITLE
Exclude a particular file/files?

### ISSUE THREAD

**Issue by SohailAQ** [un1t/django-cleanup#91]
I have a couple of default image files in my media folder, 'default_m.png' and 'default_f.png' which are assigned to the user as soon as the user is created.

When the user edits his/her profile and uploads a new profile image, the uploaded image is stored in media/profile/ and the default images, (media/default_m.png and media/default_f.png) are deleted.

I would like to exclude these two files from being deleted.

**Comment by vinnyrose** [comment]
The code only supports one default image. I would advise that the profile image field be nullable as the default and you simply show one of the default images when the profile image is null. With that change, and if desirable, you could move the default images out of the media root and into the static files.
